import {
  Layers,
  Users,
  Settings,
  BarChart2,
  Inbox,
  BookOpen,
  Folder,
  FileText,
  Star,
  HelpCircle,
  GraduationCap,
  Dices,
  Presentation,
  LayoutGrid,
  Swords,
  Mic,
  Timer,
  Palette,
  BookOpenCheck,
  BookA,
  Gamepad2,
  Joystick,
  Landmark,
  Award,
  Briefcase,
  Sparkles,
  Calculator,
  ClipboardCheck,
  ShoppingBag,
  Calendar,
  NotebookPen,
} from 'lucide-react';

/**
 * Apps launcher grid. Entries without a registered shell app are placeholders.
 */
export const launcherApps = [
  {
    id: 'hub',
    name: 'Hub',
    icon: Layers,
    color: 'bg-sky-500',
    description: 'Your home base for dashboard, apps, and district resources.',
  },
  {
    id: 'students',
    name: 'Students',
    icon: GraduationCap,
    color: 'bg-cyan-500',
    description: 'Browse the shared student directory and open full profiles.',
  },
  {
    id: 'classes',
    name: 'Classes',
    icon: BookOpen,
    color: 'bg-emerald-500',
    description: 'Create and manage class rosters, subjects, and grade levels.',
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    icon: Presentation,
    color: 'bg-sky-500',
    description: 'Smart whiteboard for drawing, annotating, and presenting lessons.',
  },
  {
    id: 'groups',
    name: 'Groups',
    icon: LayoutGrid,
    color: 'bg-orange-500',
    description: 'Sort, build, and save student groups with pairing preferences.',
  },
  {
    id: 'timer',
    name: 'Timer',
    icon: Timer,
    color: 'bg-emerald-500',
    description: 'Whole-class timers, stopwatches, small groups, and world clocks.',
  },
  {
    id: 'randomizer',
    name: 'Randomizer',
    icon: Dices,
    color: 'bg-violet-500',
    description: 'Pick students at random with shuffle, wheel, cards, and pull-a-name.',
  },
  {
    id: 'tiebreaker',
    name: 'TieBreaker',
    icon: Swords,
    color: 'bg-rose-500',
    description: 'Settle ties with numbers, coins, cards, challenges, and showdowns.',
  },
  {
    id: 'noisemeter',
    name: 'NoiseMeter',
    icon: Mic,
    color: 'bg-amber-400',
    description: 'Monitor classroom volume with a meter, bubbles, and a block tower.',
  },
  {
    id: 'design',
    name: 'AppGuide',
    icon: Palette,
    color: 'bg-violet-500',
    description: 'Living style guide — branding, patterns, cards, and shell chrome.',
  },
  {
    id: 'brand',
    name: 'HubBrand',
    icon: Sparkles,
    color: 'bg-rose-500',
    description: 'Edu.Hub product brand — logo, naming, and identity guidelines.',
  },
  {
    id: 'earlyliteracy',
    name: 'EarlyLiteracy',
    icon: BookOpenCheck,
    color: 'bg-sky-500',
    description:
      'Phonics tools — blending board, word work mat, and more for early reading.',
  },
  {
    id: 'dictionary',
    name: 'Dictionary',
    icon: BookA,
    color: 'bg-sky-500',
    description:
      'Look up a word even if the spelling is off — definitions and public-domain pictures.',
  },
  {
    id: 'games',
    name: 'Games',
    icon: Gamepad2,
    color: 'bg-indigo-500',
    description:
      'Classroom Wordle and other quick literacy games for word practice.',
  },
  {
    id: 'arcade',
    name: 'Arcade',
    icon: Joystick,
    color: 'bg-lime-500',
    description:
      'For-fun classic games — Solitaire and more so kids stay in Edu.Hub.',
  },
  {
    id: 'bank',
    name: 'Bank',
    icon: Landmark,
    color: 'bg-red-500',
    description:
      'Classroom economy — balances, payday, and transactions.',
  },
  {
    id: 'behavior',
    name: 'Behavior',
    icon: Award,
    color: 'bg-indigo-500',
    description:
      'ClassDojo-style points tracker. Optionally sync awards to Bank dollars.',
  },
  {
    id: 'jobs',
    name: 'Jobs',
    icon: Briefcase,
    color: 'bg-amber-500',
    description:
      'Classroom roles and salaries. Sync assignments to Bank for payday.',
  },
  {
    id: 'attendance',
    name: 'Attendance',
    icon: ClipboardCheck,
    color: 'bg-emerald-500',
    description:
      'Daily attendance, lunch count, reports, and class attendance goals.',
  },
  {
    id: 'store',
    name: 'Store',
    icon: ShoppingBag,
    color: 'bg-orange-500',
    description:
      'Classroom rewards catalog. Redeem from Bank or Behavior when connected.',
  },
  {
    id: 'mathTools',
    name: 'MathTools',
    icon: Calculator,
    color: 'bg-blue-500',
    description:
      'Hands-on math desks — Money and Clock — also available from Bank and Timer.',
  },
  {
    id: 'district',
    name: 'District',
    icon: Users,
    color: 'bg-pink-500',
    description: 'District tools and collaboration — coming soon.',
  },
  {
    id: 'admin',
    name: 'Admin',
    icon: Settings,
    color: 'bg-teal-500',
    description: 'Administrative controls for your workspace — coming soon.',
  },
  {
    id: 'analytics',
    name: 'Analytics',
    icon: BarChart2,
    color: 'bg-orange-500',
    description: 'Track engagement and performance insights — coming soon.',
  },
  {
    id: 'mail',
    name: 'Mail',
    icon: Inbox,
    color: 'bg-indigo-500',
    description: 'School messaging and inbox — coming soon.',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    icon: Calendar,
    color: 'bg-sky-500',
    description:
      'Class schedules, specialist rotations, snow-day pause, and countdowns.',
  },
  {
    id: 'paper',
    name: 'Paper',
    icon: NotebookPen,
    color: 'bg-sky-600',
    description: 'Print lined, dotted, grid, and other classroom paper.',
  },
  {
    id: 'files',
    name: 'Files',
    icon: Folder,
    color: 'bg-blue-400',
    description: 'Store and share classroom files — coming soon.',
  },
  {
    id: 'tasks',
    name: 'Tasks',
    icon: FileText,
    color: 'bg-cyan-600',
    description: 'To-dos and classroom task lists — coming soon.',
  },
  {
    id: 'grades',
    name: 'Grades',
    icon: Star,
    color: 'bg-amber-500',
    description: 'Gradebook and assessment tracking — coming soon.',
  },
  {
    id: 'support',
    name: 'Support',
    icon: HelpCircle,
    color: 'bg-pink-500',
    description: 'Help center and support requests — coming soon.',
  },
];
